### ISSUE TITLE
How to run this project on a sample file?

### ISSUE THREAD

**Issue by SaadBazaz** [alpoktem/MachineDub#1]
Hey there, thanks for the repo.
Would appreciate if there was some documentation on how to run this over some demos.

**Comment by ai-nikolai** [comment]
@SaadBazaz @alpoktem I haven't tried myself, but any luck on this?

**Comment by SaadBazaz** [comment]
@ai-nikolai None. Dead repo

**Comment by alpoktem** [comment]
Hi, this repo serves only as a complement to the published paper. It's not maintained beyond publishing it's experimental results.

**Comment by ai-nikolai** [comment]
Perfect. Thanks for the answer. 

Where in the code would you go about to try it out on a new .wav file?

Do you think this method is competetive with newer methods (i.e. if tried with bigger LMs)?

**Comment by alpoktem** [comment]
Hi @ai-nikolai, I haven't even looked at the code since 5 years so sorry I cannot help you with that. But I can tell that different methods are used for different processes (prosodic pause extraction, alignment, TTS). There's no unique pipeline to get from wave to wave file.
